# Generated by Django 4.1.2 on 2022-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.CharField(max_length=5)),
                ('m1', models.CharField(max_length=5)),
                ('m2', models.CharField(max_length=5)),
                ('m3', models.CharField(max_length=5)),
                ('m4', models.CharField(max_length=5)),
                ('m5', models.CharField(max_length=5)),
            ],
        ),
    ]
